services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - private
      - public
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./services/nginx/servers.conf:/etc/nginx/conf.d/servers.conf:ro
      - ./services/blog:/usr/share/nginx/html:ro
      - ./certbot/conf:/etc/letsencrypt:ro

  certbot:
    image: certbot/dns-cloudflare
    profiles: ["certbot"]
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/cloudflare.ini:/cloudflare.ini:ro

  postgis:
    image: kartoza/postgis:17-3.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - private

  geohub:
    image: ghcr.io/rikferreira/geohub:sha-be3a03df96de4d19c3319c19ae1828b169f9909d
    restart: unless-stopped
    environment:
      ARCGIS_USERNAME: ${ARCGIS_USERNAME}
      ARCGIS_PASSWORD: ${ARCGIS_PASSWORD}
    networks:
      - private

volumes:
  pgdata:
    driver: local
  
networks:
  public:
    driver: bridge
  private:
    driver: bridge
